<a href="https://colab.research.google.com/github/dvasylyshyn/Gene_Expression/blob/main/KNeighbors_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
import io
from google.colab import files
uploaded = files.upload()

Saving data2.csv to data2.csv


In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['data2.csv']))

In [ ]:
X=df.iloc[:,4:9764]
y=df.iloc[:,[2]]

In [ ]:
y.value_counts()

Class
BRCA     151
KIRC     146
LUAD     141
PRAD     136
COAD      78
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.50, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train.values.ravel())

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

In [ ]:
print("Confusion Matrix:\n", + cm)
print()
print("Accuracy Score: ", + ac)

Confusion Matrix:
 [[66  0  0  2  0]
 [ 0 39  0  0  0]
 [ 0  0 77  0  0]
 [ 1  0  0 74  0]
 [ 1  0  0  0 66]]

Accuracy Score:  0.9877300613496932


In [ ]:
from sklearn import metrics

In [ ]:
#accuracy
print("acuracy:", metrics.accuracy_score(y_test,y_pred=y_pred))
print("precision:", metrics.precision_score(y_test,y_pred=y_pred,average="micro"))
print("recall" , metrics.recall_score(y_test,y_pred=y_pred,average="micro"))
print(metrics.classification_report(y_test, y_pred=y_pred))

acuracy: 0.9877300613496932
precision: 0.9877300613496932
recall 0.9877300613496932
              precision    recall  f1-score   support

        BRCA       0.97      0.97      0.97        68
        COAD       1.00      1.00      1.00        39
        KIRC       1.00      1.00      1.00        77
        LUAD       0.97      0.99      0.98        75
        PRAD       1.00      0.99      0.99        67

    accuracy                           0.99       326
   macro avg       0.99      0.99      0.99       326
weighted avg       0.99      0.99      0.99       326

